import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import {
    BRAND_RAMP_ENGINE_VERSION,
    BRAND_RAMP_PAIRINGS,
    BRAND_RAMP_ROLES,
    contrast,
    generateBrandRamp,
    brandRampSnap,
    brandRampByHeadroom,
    type BrandRampTheme,
} from '../brand-ramp';

/**
 * The TypeScript half of the brand-ramp dual-engine guard (ADR-0014, H23a1).
 *
 * `tests/fixtures/brand-ramp.json` is generated by `app/Support/Branding/BrandRampGenerator.php`, which is
 * the AUTHORITATIVE engine — four of the five surfaces that consume a ramp are server-rendered, so the
 * browser cannot be the source of truth. `brand-ramp.ts` exists only so the admin picker (H23a2) can
 * preview a ramp per keystroke instead of per round trip, and a preview that disagreed with what gets
 * saved would be worse than no preview: the tenant would approve one ramp and receive another.
 *
 * So this file asserts the port is EXACT — same hexes, same ratios, same pairing list, same version. It is
 * the mirror of `tests/Unit/Branding/BrandRampParityTest.php`, which drives the same fixture through PHP.
 *
 * **A failure here is a port bug, not a fixture problem.** Regenerating the fixture to make this pass
 * would delete the only evidence the two engines agree.
 */

const here = (p: string) => fileURLToPath(new URL(p, import.meta.url));

interface Vector {
    name: string;
    note?: string;
    input: string;
    engine_version: number;
    tokens: Record<BrandRampTheme, Record<string, string>>;
    measurements: { theme: BrandRampTheme; pairing: string; ratio: number; min: number }[];
}

const vectors = JSON.parse(
    readFileSync(here('../../../../../tests/fixtures/brand-ramp.json'), 'utf8'),
) as Vector[];

describe('brand-ramp PHP↔TS parity', () => {
    it('reads a non-trivial fixture with unique names', () => {
        // Anti-vacuity: a fixture that failed to load, or that silently shrank to one vector, would make
        // every `it.each` below pass while proving nothing.
        expect(vectors.length).toBeGreaterThanOrEqual(12);
        expect(new Set(vectors.map((v) => v.name)).size).toBe(vectors.length);
    });

    it.each(vectors.map((v) => [v.name, v] as const))('derives %s byte-identically', (_name, vector) => {
        const result = generateBrandRamp(vector.input);

        expect(result.tokens).toEqual(vector.tokens);
        expect(result.engineVersion).toBe(vector.engine_version);
    });

    it.each(vectors.map((v) => [v.name, v] as const))('measures %s identically to PHP', (_name, vector) => {
        const result = generateBrandRamp(vector.input);

        // The fixture stores ratios rounded to the two decimals §4.1 prints, so round before comparing —
        // this is a check that the two engines agree about the NUMBERS, and the eighth decimal place of a
        // WCAG ratio is not a number anyone has an opinion about.
        expect(result.measurements.map((m) => ({ ...m, ratio: Math.round(m.ratio * 100) / 100 }))).toEqual(
            vector.measurements,
        );
    });

    it('agrees with PHP about the engine version', () => {
        // A version bump on one side only would silently start storing ramps stamped with a version the
        // other engine never produced.
        expect(BRAND_RAMP_ENGINE_VERSION).toBe(vectors[0].engine_version);
    });

    it('encodes exactly the seventeen §4.1 pairings, nine light and eight dark', () => {
        expect(BRAND_RAMP_PAIRINGS).toHaveLength(17);
        expect(BRAND_RAMP_PAIRINGS.filter((p) => p.theme === 'light')).toHaveLength(9);
        expect(BRAND_RAMP_PAIRINGS.filter((p) => p.theme === 'dark')).toHaveLength(8);
    });

    it('defines all six roles in both themes for every vector', () => {
        for (const vector of vectors) {
            for (const theme of ['light', 'dark'] as const) {
                expect(Object.keys(vector.tokens[theme]).sort()).toEqual([...BRAND_RAMP_ROLES].sort());
            }
        }
    });
});

describe('brand-ramp accessibility floor', () => {
    it.each(vectors.map((v) => [v.name, v] as const))('satisfies every §4.1 pairing for %s', (_name, vector) => {
        // Re-measured in TypeScript from the STORED hexes rather than trusting the stored ratios: this is
        // the assertion that would catch a fixture hand-edited to make a red build green.
        const grounds = {
            light: { surface: '#FFFFFF', canvas: '#F3F4F1', ink: '#0E1620' },
            dark: { surface: '#123350', canvas: '#0C2337', ink: '#EAF1F6' },
        } as const;

        for (const pairing of BRAND_RAMP_PAIRINGS) {
            const token = vector.tokens[pairing.theme][pairing.role];
            const against =
                pairing.against === 'on_primary' ? '#FFFFFF' : grounds[pairing.theme][pairing.against];

            expect(
                contrast(token, against),
                `${vector.name} / ${pairing.theme} / ${pairing.label}`,
            ).toBeGreaterThanOrEqual(pairing.min);
        }
    });
});

describe('brand-ramp engine behaviour', () => {
    it('reproduces the ratified Teal accent token-for-token', () => {
        // The same anchor claim the PHP suite makes, asserted independently here: fed Teal's hue the
        // engine re-derives the two tokens G11 hand-picked and hand-verified.
        const teal = generateBrandRamp('#1B5E5E');

        expect(teal.tokens.light.bg).toBe('#1B5E5E'); // --mds-accent-teal-600
        expect(teal.tokens.light.tint).toBe('#E6F2F2'); // --mds-accent-teal-50
    });

    it('gives every achromatic input the same ramp', () => {
        const black = generateBrandRamp('#000000').tokens;

        expect(generateBrandRamp('#FFFFFF').tokens).toEqual(black);
        expect(generateBrandRamp('#808080').tokens).toEqual(black);
    });

    it('normalises case and surrounding whitespace', () => {
        expect(generateBrandRamp('  #1b5e5e  ').input).toBe('#1B5E5E');
    });

    it.each(['', '#FFF', 'FFFFFF', '#GGGGGG', '#1234567', 'rgb(1,2,3)'])('refuses %s', (input) => {
        expect(() => generateBrandRamp(input)).toThrow();
    });
});

describe('snap disclosure helpers', () => {
    it('reports an adjustment when the engine had to move the input', () => {
        // A maximally saturated yellow cannot carry white button text at its own lightness, so the engine
        // drives it dark. This is the case the disclosure exists for.
        const snap = brandRampSnap(generateBrandRamp('#FFE14D'));

        expect(snap.input).toBe('#FFE14D');
        expect(snap.derived).not.toBe('#FFE14D');
        expect(snap.adjusted).toBe(true);
    });

    it('reports NO adjustment when the input is already usable', () => {
        // Teal is a shipped accent and the engine re-derives it exactly, so a tenant entering it is told
        // their colour was used as-is. If `adjusted` compared against any token other than the light fill
        // this would be false, and the card would claim an adjustment on every colour ever entered.
        const snap = brandRampSnap(generateBrandRamp('#1B5E5E'));

        expect(snap.derived).toBe('#1B5E5E');
        expect(snap.adjusted).toBe(false);
    });

    it('orders measurements by headroom, worst first', () => {
        const ordered = brandRampByHeadroom(generateBrandRamp('#C0392B').measurements);

        expect(ordered).toHaveLength(17);

        const headroom = ordered.map((m) => m.ratio - m.min);
        expect(headroom).toEqual([...headroom].sort((a, b) => a - b));

        // Worst-first is not the same as lowest-ratio-first, and that is the point: a 4.6:1 that needs 4.5
        // is tighter than a 5.2:1 that needs 3.0. Assert the two orderings actually differ here, or this
        // test would pass against a naive sort-by-ratio.
        const byRatio = [...ordered].sort((a, b) => a.ratio - b.ratio);
        expect(ordered.map((m) => m.pairing)).not.toEqual(byRatio.map((m) => m.pairing));
    });

    it('does not mutate the array it is given', () => {
        const measurements = generateBrandRamp('#C0392B').measurements;
        const before = measurements.map((m) => m.pairing);

        brandRampByHeadroom(measurements);

        expect(measurements.map((m) => m.pairing)).toEqual(before);
    });
});
