// Build the Meridian design tokens from the blueprint palette into:
//   dist/tokens.css  — CSS custom properties on :root (semantic layer references primitives)
//   dist/tokens.ts   — typed map of every token name -> var() reference, for TS consumers
//
// Dark mode + personalization (data-theme-mode / data-accent) live in src/theme/theme-overrides.css
// as a re-pointing of the SEMANTIC layer only (see docs/ux/design-system-reference.md §2.9).

import StyleDictionary from 'style-dictionary';

StyleDictionary.registerFormat({
    name: 'meridian/ts',
    format: ({ dictionary }) => {
        const lines = dictionary.allTokens.map((token) => {
            const kebab = token.path.join('-');
            const camel = kebab.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
            return `    ${JSON.stringify(camel)}: 'var(--mds-${kebab})',`;
        });

        return [
            '// AUTO-GENERATED by build-tokens.mjs — do not edit by hand.',
            'export const mdsToken = {',
            lines.join('\n'),
            '} as const;',
            '',
            'export type MdsTokenName = keyof typeof mdsToken;',
            '',
        ].join('\n');
    },
});

const sd = new StyleDictionary({
    source: ['tokens/**/*.json'],
    platforms: {
        css: {
            transformGroup: 'css',
            prefix: 'mds',
            buildPath: 'dist/',
            files: [
                {
                    destination: 'tokens.css',
                    format: 'css/variables',
                    options: { selector: ':root', outputReferences: true },
                },
            ],
        },
        ts: {
            transformGroup: 'css',
            prefix: 'mds',
            buildPath: 'dist/',
            files: [
                {
                    destination: 'tokens.ts',
                    format: 'meridian/ts',
                },
            ],
        },
    },
});

await sd.buildAllPlatforms();
