<?php

declare(strict_types=1);

namespace App\Exceptions\Attachments;

use App\Support\Api\ApiErrorResponse;
use Illuminate\Http\JsonResponse;
use RuntimeException;

/**
 * A rejection from an attachment write path — a bad MIME type, an over-size file, an unknown or
 * non-media target field (Increment G6), or a malware verdict on generated bytes (Increment H17).
 * Self-rendering via {@see ApiErrorResponse} so the upload controllers stay thin channel adapters
 * and return the same `{ error: { code, message } }` envelope the rest of the API surface uses.
 *
 * H17 note: {@see infected()} is thrown from inside a queued job, where there is no request and
 * the rendered envelope is never used. It lives here anyway because the family is the attachment
 * write path, not the HTTP channel — and a later synchronous PDF endpoint gets the right envelope
 * for free rather than inventing a second exception with a different code for the same fault.
 */
final class AttachmentException extends RuntimeException
{
    public function __construct(
        public readonly int $status,
        public readonly string $errorCode,
        string $message,
    ) {
        parent::__construct($message);
    }

    public static function tooLarge(int $maxBytes): self
    {
        return new self(422, 'attachment_too_large', "This file exceeds the field's maximum size of {$maxBytes} bytes.");
    }

    public static function mimeRejected(string $mime): self
    {
        return new self(422, 'attachment_mime_rejected', "Files of type {$mime} are not accepted for this field.");
    }

    public static function fieldNotFound(): self
    {
        return new self(422, 'attachment_field_unknown', 'The target field does not exist or does not accept media.');
    }

    public static function storeFailed(): self
    {
        return new self(500, 'attachment_store_failed', 'The file could not be stored. Please try again.');
    }

    /**
     * A generated artifact failed its malware scan (Increment H17).
     *
     * Distinct from every factory above: those reject something a client SENT, this rejects
     * something the platform ITSELF produced. That should be impossible, which is exactly why it
     * is loud — a scanner flagging our own render means either the scanner or the renderer is
     * compromised, and the correct response is to write nothing and fail the job.
     */
    public static function infected(string $subjectId): self
    {
        return new self(500, 'attachment_infected_artifact', "The generated file for {$subjectId} failed its malware scan and was discarded.");
    }

    public function render(): JsonResponse
    {
        return ApiErrorResponse::make($this->status, $this->errorCode, $this->getMessage());
    }
}
