<?php

declare(strict_types=1);

use App\Support\Tenancy\TenantIsolation;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

/**
 * The read half of the PLATFORM audit viewer (Increment I7b, PRD Feature #12 / RBAC §9).
 * `2026_08_06_000003_apply_superadmin_bypass_to_audits.php` deferred it to "I7/I11"; this is I7. Since I5,
 * `SuperAdminService::updatePlatformSettings()` has been writing `audits` rows with
 * `tenant_id = NULL` that **no surface in the product could read** — write-only-and-retained. `GET /admin/audit-log`
 * is the surface, and this migration is what lets it see anything.
 *
 * ── (a) WHY IT DEVIATES FROM applySuperAdminBypass() ────────────────────────────────────────────────────
 * {@see TenantIsolation::superAdminBypassSql()} emits `USING (current_setting('app.is_superadmin_context', true) = 'true')`
 * — an **unrestricted** gate. That is correct on a table whose base shape is `nullable_global`, where the
 * platform slice is already readable by every tenant and widening the elevated role adds nothing it could
 * not already reach. It is **wrong here**: `audits` is `appendOnly` and strictly tenant-scoped, so the
 * generic policy would hand the platform operator **every tenant's complete history** — every form title,
 * every reviewer's `returned_reason`, every membership change in the deployment — bought to display a
 * handful of platform-settings rows. **The helper's gate is a DEFAULT, NOT A CONTRACT.** The conjunct
 * `AND tenant_id IS NULL` is the entire difference between a platform ledger viewer and a cross-tenant
 * surveillance tool, so `audits` takes {@see TenantIsolation::platformRowsBypass()} instead.
 *
 * It is a GENERATED shape, not hand-written SQL, because ADR-0002 §D2 requires exactly that ("policies are
 * generated by a reusable migration helper … not hand-written per table"). `tests/Unit/TenantIsolationSqlTest.php`
 * pins the emitted string; `tests/Feature/Audit/PlatformAuditRlsTest.php` pins the LIVE policy's `qual`
 * from `pg_policies`, which is the only such assertion in the suite. Between them, a dropped conjunct is a
 * merge-blocking failure rather than a review miss.
 *
 * ── (b) THIS IS NOT THE WIDENING 2026_08_06_000003 FORBIDS ──────────────────────────────────────────────
 * That file says: *"do not 'fix' the invisibility by widening the SELECT policy."* The invisibility it names
 * is **tenant-facing**, and it is untouched — `audits_tenant_select` is not modified, not dropped, not
 * recreated, and a tenant connection sees exactly what it saw before this migration ran. What is added is a
 * SECOND, additive, role-scoped policy that Postgres OR-composes only for `meridian_superadmin`, only while
 * the GUC is `'true'`, and even then only over `tenant_id IS NULL`. **Both directions of the wall stand: a
 * tenant cannot read platform rows, and the operator cannot read tenant rows.** `PlatformAuditRlsTest`
 * asserts both, and separately asserts that `audits_tenant_select`'s own `qual` is unchanged.
 *
 * ── (c) THE APPEND-ONLY GUARANTEE IS INTACT ─────────────────────────────────────────────────────────────
 * **No UPDATE policy. No DELETE policy. For any role, including this one.** Under FORCE ROW LEVEL SECURITY a
 * command with no matching policy is denied for every role, and that absence IS the enforcement of
 * data-dictionary §13's "immutable, never deleted". The GRANT below is `SELECT` only, so
 * `has_table_privilege('meridian_superadmin', 'audits', 'UPDATE')` stays false — asserted, not assumed.
 * The standing prohibition is repeated verbatim: **no UPDATE or DELETE policy may ever be added to this
 * table by anyone, for any role.**
 *
 * ── (d) POLICY NAME ─────────────────────────────────────────────────────────────────────────────────────
 * `audits_platform_select`, deliberately outside the `audits_superadmin_%` prefix that `2026_08_06_000003`'s
 * `down()` sweeps. A shared prefix would let that rollback drop this policy while the GRANT below survived,
 * and the viewer would then render **zero rows with no error** under copy reading "nobody has saved a change
 * on the Platform page yet" — a plausible lie on a compliance surface. The reasoning lives in full on
 * {@see TenantIsolation::platformRowsBypass()}.
 *
 * Runs on the default `meridian_app` connection (it owns `audits`). Creates no table, so the migration
 * linter does not require withTenantIsolation() here.
 */
return new class extends Migration
{
    public function up(): void
    {
        $role = (string) config('database.connections.pgsql_superadmin.username', 'meridian_superadmin');
        if (preg_match('/^[a-z_][a-z0-9_]*$/', $role) !== 1) {
            throw new RuntimeException("Unsafe pgsql_superadmin role name: {$role}");
        }

        // Table privileges are checked BEFORE RLS: without this the console's query dies "permission
        // denied" before the policy is ever consulted. SELECT only — the INSERT grant stays where
        // 2026_08_06_000003 put it, and the role holds no UPDATE or DELETE on this table.
        DB::statement("GRANT SELECT ON audits TO {$role}");

        TenantIsolation::platformRowsBypass('audits', ['SELECT']);
    }

    public function down(): void
    {
        $role = (string) config('database.connections.pgsql_superadmin.username', 'meridian_superadmin');
        if (preg_match('/^[a-z_][a-z0-9_]*$/', $role) !== 1) {
            throw new RuntimeException("Unsafe pgsql_superadmin role name: {$role}");
        }

        /** @var list<object{policyname: string}> $policies */
        $policies = DB::select("SELECT policyname FROM pg_policies WHERE tablename = 'audits' AND policyname LIKE 'audits_platform_%'");
        foreach ($policies as $policy) {
            DB::statement('DROP POLICY IF EXISTS '.$policy->policyname.' ON audits');
        }

        // Safe beside 2026_08_06_000003: that migration granted INSERT, and revoking SELECT leaves it.
        DB::statement("REVOKE SELECT ON audits FROM {$role}");
    }
};
