<?php

declare(strict_types=1);

use App\Enums\DomainEventType;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

/**
 * I9c adds one {@see DomainEventType} case — `submission.updated`, announced when a finalized submission's
 * answers are corrected — so the `webhook_deliveries.event_type` CHECK, generated from
 * {@see DomainEventType::values()} when H13a created the table and last regenerated by I3, has to be
 * regenerated again from the now-8-value enum.
 *
 * The reasoning is I3's verbatim and it still holds: subscription validation is
 * `Rule::in(DomainEventType::values())` across eight FormRequests, so the moment the enum grows a tenant can
 * legally subscribe an endpoint to `submission.updated` — and on an already-migrated database the fan-out
 * INSERT would then die with SQLSTATE 23514 against a constraint frozen at seven values. `E2eSeeder`
 * subscribes its demo endpoint to `DomainEventType::values()` wholesale, so the demo tenant hits it first
 * and the failure would surface in the seeded fixture rather than in a tenant's real integration.
 *
 * Alter-only (no `Schema::create`) → scripts/migration-lint.php short-circuits.
 */
return new class extends Migration
{
    /** The one case this migration adds — named once, used by both directions. */
    private const array ADDED = [
        DomainEventType::SubmissionUpdated,
    ];

    public function up(): void
    {
        $this->recreate(DomainEventType::values());
    }

    public function down(): void
    {
        // Recreate the CHECK without the I9c case (the seven pre-I9c values).
        $this->recreate(array_values(array_map(
            static fn (DomainEventType $case): string => $case->value,
            array_filter(
                DomainEventType::cases(),
                static fn (DomainEventType $case): bool => ! in_array($case, self::ADDED, true),
            )
        )));
    }

    /**
     * @param  list<string>  $values
     */
    private function recreate(array $values): void
    {
        $eventTypes = implode(', ', array_map(
            static fn (string $value): string => "'".$value."'",
            $values
        ));

        DB::statement('ALTER TABLE webhook_deliveries DROP CONSTRAINT webhook_deliveries_event_type_check');
        DB::statement(
            'ALTER TABLE webhook_deliveries ADD CONSTRAINT webhook_deliveries_event_type_check '
            ."CHECK (event_type IN ({$eventTypes}))"
        );
    }
};
