<?php

declare(strict_types=1);

use App\Exceptions\Branding\BrandRampException;
use App\Support\Branding\BrandRamp;
use App\Support\Branding\BrandRampGenerator;
use App\Support\Branding\ColorSpace;

/**
 * The PHP half of the brand-ramp dual-engine guard (ADR-0014, H23a1).
 *
 * `packages/design-system/src/theme/brand-ramp.ts` is a hand-written port of
 * {@see BrandRampGenerator}, and the admin picker (H23a2) renders its output as a live preview while PHP
 * decides what is actually stored. A disagreement between the two would be worse than having no preview at
 * all: the tenant approves one ramp and receives a different one. `tests/fixtures/brand-ramp.json` is
 * generated by the PHP engine and asserted hex-for-hex by BOTH this file and `brand-ramp.test.ts` — the
 * H6a/H6b piping-formatter precedent.
 *
 * The fixture lives in `tests/fixtures/`, deliberately NOT `tests/golden/`: it has no `grammar_version`
 * key and no manifest entry, so it moves neither the 296-site count nor the 114-vector total. That is the
 * H21a amendment-A6 precedent that `tests/fixtures/condition-serializer.json` and
 * `tests/fixtures/step-projection.json` already follow.
 *
 * **When a vector here fails, regenerating the fixture is almost always the wrong fix.** The fixture is
 * the record of what the shipped engine produces; a diff means either a deliberate engine change (which
 * takes a {@see BrandRampGenerator::VERSION} bump and a re-derivation plan for stored ramps) or a bug.
 */

/**
 * @return list<array{name: string, note?: string, input: string, engine_version: int, tokens: array<string, array<string, string>>, measurements: list<array{theme: string, pairing: string, ratio: float, min: float}>}>
 */
function brandRampVectors(): array
{
    // A plain path, not base_path(): this runs at Pest COLLECTION time, before the container exists.
    $path = dirname(__DIR__, 2).'/fixtures/brand-ramp.json';
    $decoded = json_decode((string) file_get_contents($path), true, 512, JSON_THROW_ON_ERROR);

    /** @var list<array{name: string, note?: string, input: string, engine_version: int, tokens: array<string, array<string, string>>, measurements: list<array{theme: string, pairing: string, ratio: float, min: float}>}> $decoded */
    return $decoded;
}

it('re-derives every fixture vector byte-identically', function (array $vector): void {
    $ramp = (new BrandRampGenerator)->generate($vector['input']);

    expect($ramp->tokens)->toBe($vector['tokens'])
        ->and($ramp->engineVersion)->toBe($vector['engine_version']);
})->with(array_combine(
    array_column(brandRampVectors(), 'name'),
    array_map(static fn (array $v): array => [$v], brandRampVectors()),
));

it('reproduces the ratified Teal accent FILL token-for-token', function (): void {
    // The anchor claim of ADR-0014 §D4: the targets encode the design system's own judgment, not an
    // author's taste. Fed Teal's hue, the engine independently arrives at the fill a human hand-picked
    // and hand-verified in G11, byte-identically.
    $ramp = (new BrandRampGenerator)->generate('#1B5E5E');

    expect($ramp->token('light', 'bg'))->toBe('#1B5E5E'); // --mds-accent-teal-600
});

it('no longer reproduces the ratified Teal TINT — and that is a property of the grounds, not a regression', function (): void {
    // ⚠️ THE TINT HALF OF §D4's BYTE-IDENTITY CLAIM DIED IN JR1, AND THE REASON IS WORTH MORE THAN THE
    // CLAIM WAS. The two halves were never equally robust:
    //
    //   · `bg` is searched against ON_PRIMARY, which is #FFFFFF — a ground that CANNOT move. That half
    //     still holds byte-for-byte and always will.
    //   · `tint` is searched against the light `ink` ground, which is `neutral-900`. JR1 moved the neutral
    //     ramp (#0E1620 -> #121A2A), so the lightness satisfying "15.9:1 against ink" moved with it, and
    //     the engine now derives #EBF7F7 where G11's human hand-picked #E6F2F2.
    //
    // `--mds-accent-teal-50` is deliberately NOT updated to #EBF7F7 to make this test green again. Doing
    // that would leave the assertion comparing the engine against a number copied FROM the engine, which
    // is precisely the evidential value §D4 was claiming — an independent human choice and a machine
    // agreeing. A circular assertion that reads like corroboration is worse than an honest divergence.
    //
    // The two are 5 units per channel apart and both clear ink-on-tint comfortably; the divergence is
    // recorded, not papered over.
    $ramp = (new BrandRampGenerator)->generate('#1B5E5E');

    expect($ramp->token('light', 'tint'))->toBe('#EBF7F7')
        ->and(round(ColorSpace::contrast('#121A2A', $ramp->token('light', 'tint')), 2))
        ->toBeGreaterThanOrEqual(4.5);
});

it('reproduces §4.1 rows 1-3 for Teal to two decimals', function (): void {
    $ramp = (new BrandRampGenerator)->generate('#1B5E5E');
    $light = $ramp->tokens['light'];

    expect(round(ColorSpace::contrast('#FFFFFF', $light['bg']), 2))->toBe(7.48)
        ->and(round(ColorSpace::contrast('#FFFFFF', $light['bg_hover']), 2))->toBe(9.40)
        ->and(round(ColorSpace::contrast('#FFFFFF', $light['bg_active']), 2))->toBe(12.10);
});

it('satisfies every §4.1 pairing for every fixture vector', function (array $vector): void {
    // Belt and braces over the generator's own deny-by-default check: this re-measures from the STORED
    // hexes, so it would catch a generator that validated one ramp and returned another.
    $ramp = (new BrandRampGenerator)->generate($vector['input']);

    foreach ($ramp->measurements as $measurement) {
        expect($measurement['ratio'])->toBeGreaterThanOrEqual(
            $measurement['min'],
            sprintf('%s / %s', $measurement['theme'], $measurement['pairing']),
        );
    }
})->with(array_combine(
    array_column(brandRampVectors(), 'name'),
    array_map(static fn (array $v): array => [$v], brandRampVectors()),
));

it('encodes exactly the seventeen pairings of design-system-reference.md §4.1', function (): void {
    // §4.1's Teal table is 17 rows. This list is that table with the hue removed, so the count is a
    // correspondence with a document, not an implementation detail — light row 6 duplicates row 5's
    // colour pair at a lower floor and is kept for exactly that reason.
    expect(BrandRampGenerator::pairings())->toHaveCount(17);

    $byTheme = array_count_values(array_column(BrandRampGenerator::pairings(), 'theme'));

    expect($byTheme)->toBe(['light' => 9, 'dark' => 8]);
});

it('keeps BrandRamp::ROLES in step with what the generator actually produces', function (): void {
    // The constant is not decoration: H23a2 stores against it and H23a3 iterates it to emit the six custom
    // properties. A role added to the generator but not to ROLES — or renamed in one place — would make the
    // CSS emitter silently skip a token, which renders as "the hover colour didn't take" and nothing else.
    // The TypeScript twin asserts its own mirror; this is the PHP half of that guard.
    $tokens = (new BrandRampGenerator)->generate('#1B5E5E')->tokens;

    expect(array_keys($tokens))->toBe(BrandRamp::THEMES);

    foreach (BrandRamp::THEMES as $theme) {
        expect(array_keys($tokens[$theme]))->toEqualCanonicalizing(BrandRamp::ROLES);
    }
});

it('gives every achromatic input the same ramp', function (): void {
    // Lightness is discarded and re-derived per role, so black, white and mid-grey carry identical
    // information: no hue. If these ever diverge, the engine has started reading the input's lightness —
    // which is the one property it must not preserve, because lightness IS contrast.
    $generator = new BrandRampGenerator;

    $black = $generator->generate('#000000')->tokens;
    $white = $generator->generate('#FFFFFF')->tokens;
    $grey = $generator->generate('#808080')->tokens;

    expect($white)->toBe($black)->and($grey)->toBe($black);
});

it('snaps an out-of-gamut chroma rather than refusing the colour', function (): void {
    // The B-snap decision (ADR-0014 §D3), as a test: a maximally saturated yellow is exactly the input a
    // strict picker refuses. Here it produces a compliant ramp whose light fill has been driven dark
    // enough to carry white text, which is honest and is what the UI discloses.
    $ramp = (new BrandRampGenerator)->generate('#FFE14D');

    expect(ColorSpace::contrast('#FFFFFF', $ramp->token('light', 'bg')))->toBeGreaterThanOrEqual(4.5);

    // And the snap is real: the derived fill is nothing like the input the tenant typed.
    expect($ramp->token('light', 'bg'))->not->toBe('#FFE14D');
});

it('never refuses a hue', function (): void {
    // The monotonicity argument in BrandRampGenerator's docblock, exercised rather than asserted: every
    // 5° step around the wheel at maximum chroma must produce a compliant ramp. If any hue could fail,
    // BrandRampException::pairingFailed would surface here and the "never refuses" promise in the ADR
    // would be false.
    $generator = new BrandRampGenerator;

    for ($hue = 0; $hue < 360; $hue += 5) {
        $input = ColorSpace::oklchToHex(0.6, 0.37, (float) $hue);

        expect(fn (): BrandRamp => $generator->generate($input))->not->toThrow(BrandRampException::class);
    }
});

it('refuses a malformed input', function (string $input): void {
    expect(fn (): BrandRamp => (new BrandRampGenerator)->generate($input))
        ->toThrow(BrandRampException::class);
})->with(['', '#FFF', 'FFFFFF', '#GGGGGG', '#1234567', 'rgb(1,2,3)']);

it('normalises case and surrounding whitespace on the way in', function (): void {
    $ramp = (new BrandRampGenerator)->generate('  #1b5e5e  ');

    expect($ramp->input)->toBe('#1B5E5E');
});

it('round-trips through the jsonb payload without re-deriving', function (): void {
    // BrandRamp::fromArray() deliberately does not re-run the generator: a stored ramp was validated by
    // the engine version recorded beside it, and re-validating on read would fail loudly on exactly the
    // rows a future VERSION bump is meant to migrate deliberately.
    $ramp = (new BrandRampGenerator)->generate('#C0392B');
    $restored = BrandRamp::fromArray($ramp->toArray());

    expect($restored->tokens)->toBe($ramp->tokens)
        ->and($restored->input)->toBe($ramp->input)
        ->and($restored->engineVersion)->toBe($ramp->engineVersion);
});

it('rounds stored ratios to the two decimals §4.1 prints', function (): void {
    $payload = (new BrandRampGenerator)->generate('#1B5E5E')->toArray();

    foreach ($payload['measurements'] as $measurement) {
        expect($measurement['ratio'])->toBe(round($measurement['ratio'], 2));
    }
});
