/**
 * The TypeScript twin of `app/Support/Branding/BrandRampGenerator.php` (ADR-0014, H23a1).
 *
 * ── THIS FILE IS NOT AUTHORITATIVE ────────────────────────────────────────────────────────────────
 * PHP is. Four of the five surfaces that consume a brand ramp are server-rendered — the admin blade, the
 * guest blade, the dompdf PDF and transactional mail — so the browser cannot be the source of truth. This
 * exists for ONE reason: the admin picker (H23a2) shows the tenant their derived ramp and its measured
 * ratios as they type, and a round trip per keystroke is not a live preview. What the tenant SAVES is
 * always what PHP derived.
 *
 * That makes this a dual-engine parity problem of exactly the shape H6a/H6b solved for the piping
 * formatter, and it takes the same treatment: `tests/fixtures/brand-ramp.json` is generated by the PHP
 * engine and asserted, hex for hex, by both `tests/Unit/Branding/BrandRampParityTest.php` and
 * `brand-ramp.test.ts`. A preview that disagreed with the saved result would be worse than no preview —
 * the tenant would approve one ramp and receive another.
 *
 * ── THE THREE THINGS THAT KEEP THE ENGINES IDENTICAL ──────────────────────────────────────────────
 * Each is a deviation from what one would otherwise write here, and each is deliberate:
 *
 *  1. **`x ** (1 / 3)`, never `Math.cbrt`.** `Math.cbrt` is the better function — correctly rounded where
 *     `pow` is not — and that is precisely why it is wrong here: PHP has no cbrt, so using it would have
 *     the two engines computing one quantity by two routes that agree only to within a few ulp. Matching
 *     the WEAKER implementation is what makes the pair exact.
 *  2. **A fixed 1001-point lightness scan and a fixed 32-step gamut bisection.** Neither loop terminates
 *     on a tolerance. A convergence test can take a different number of iterations on two platforms and
 *     settle on opposite sides of an 8-bit rounding boundary; a fixed trip count cannot.
 *  3. **Clamp, then round.** `Math.round` is half-up and PHP's `round()` is half-away-from-zero; the two
 *     agree only on non-negative values, so the clamp to [0,1] has to happen first. Reversing them
 *     introduces a disagreement that appears on roughly one channel in a thousand — which is to say,
 *     rarely enough to pass a hand-check and fail in production.
 *
 * Every constant, target and ground below is documented on the PHP side. This file deliberately does not
 * restate that reasoning: two copies of an explanation drift, and the PHP one is the one a reader of the
 * ADR will be sent to.
 */

/** The six roles a ramp defines in each theme — mirrors `BrandRamp::ROLES`. */
export const BRAND_RAMP_ROLES = ['bg', 'bg_hover', 'bg_active', 'fg', 'tint', 'ring'] as const;

export type BrandRampRole = (typeof BRAND_RAMP_ROLES)[number];
export type BrandRampTheme = 'light' | 'dark';

export type BrandRampTokens = Record<BrandRampTheme, Record<BrandRampRole, string>>;

/** Must equal `BrandRampGenerator::VERSION`; asserted by the parity suite. */
export const BRAND_RAMP_ENGINE_VERSION = 2;

const ON_PRIMARY = '#FFFFFF';
const MAX_CHROMA = 0.11;
const MAX_TINT_CHROMA_LIGHT = 0.013;
const TEXT_MIN = 4.5;
const NON_TEXT_MIN = 3.0;

const GROUNDS: Record<BrandRampTheme, { surface: string; canvas: string; ink: string }> = {
    light: { surface: '#FFFFFF', canvas: '#F5F7FC', ink: '#121A2A' },
    dark: { surface: '#1A2130', canvas: '#0F131C', ink: '#EFF4FD' },
};

const TARGETS = {
    light: { bg: 7.5, bg_hover: 9.4, bg_active: 12.1, tint: 15.9 },
    dark: { bg: 6.4, bg_hover: 9.2, bg_active: 11.5, fg: 5.2, tint: 9.4 },
} as const;

const SRGB_LINEAR_THRESHOLD = 0.04045;
const LINEAR_SRGB_THRESHOLD = 0.0031308;

function hexToRgb(hex: string): [number, number, number] {
    const h = hex.replace('#', '');
    return [parseInt(h.slice(0, 2), 16), parseInt(h.slice(2, 4), 16), parseInt(h.slice(4, 6), 16)];
}

function channelToLinear(channel: number): number {
    const s = channel / 255;
    return s <= SRGB_LINEAR_THRESHOLD ? s / 12.92 : ((s + 0.055) / 1.055) ** 2.4;
}

function linearRgbToHex(r: number, g: number, b: number): string {
    const channel = (value: number): string => {
        const encoded = value <= LINEAR_SRGB_THRESHOLD ? value * 12.92 : 1.055 * value ** (1 / 2.4) - 0.055;
        // Clamp BEFORE rounding — see the header, point 3.
        const byte = Math.round(Math.max(0, Math.min(1, encoded)) * 255);
        return byte.toString(16).toUpperCase().padStart(2, '0');
    };

    return `#${channel(r)}${channel(g)}${channel(b)}`;
}

export function luminance(hex: string): number {
    const [r, g, b] = hexToRgb(hex);
    return 0.2126 * channelToLinear(r) + 0.7152 * channelToLinear(g) + 0.0722 * channelToLinear(b);
}

export function contrast(a: string, b: string): number {
    const la = luminance(a);
    const lb = luminance(b);
    return (Math.max(la, lb) + 0.05) / (Math.min(la, lb) + 0.05);
}

/** `#RRGGBB` → `[L, C, h]`. Achromatic input gives C = 0 and h = 0 in both engines. */
export function hexToOklch(hex: string): [number, number, number] {
    const [r8, g8, b8] = hexToRgb(hex);
    const r = channelToLinear(r8);
    const g = channelToLinear(g8);
    const b = channelToLinear(b8);

    // `** (1 / 3)`, never Math.cbrt — see the header, point 1.
    const l = (0.4122214708 * r + 0.5363325363 * g + 0.0514459929 * b) ** (1 / 3);
    const m = (0.2119034982 * r + 0.6806995451 * g + 0.1073969566 * b) ** (1 / 3);
    const s = (0.0883024619 * r + 0.2817188376 * g + 0.6299787005 * b) ** (1 / 3);

    const okL = 0.2104542553 * l + 0.793617785 * m - 0.0040720468 * s;
    const okA = 1.9779984951 * l - 2.428592205 * m + 0.4505937099 * s;
    const okB = 0.0259040371 * l + 0.7827717662 * m - 0.808675766 * s;

    return [okL, Math.hypot(okA, okB), ((Math.atan2(okB, okA) * 180) / Math.PI + 360) % 360];
}

function oklchToLinearRgb(l: number, c: number, h: number): [number, number, number] {
    const rad = (h * Math.PI) / 180;
    const okA = c * Math.cos(rad);
    const okB = c * Math.sin(rad);

    const lCube = (l + 0.3963377774 * okA + 0.2158037573 * okB) ** 3;
    const mCube = (l - 0.1055613458 * okA - 0.0638541728 * okB) ** 3;
    const sCube = (l - 0.0894841775 * okA - 1.291485548 * okB) ** 3;

    return [
        4.0767416621 * lCube - 3.3077115913 * mCube + 0.2309699292 * sCube,
        -1.2684380046 * lCube + 2.6097574011 * mCube - 0.3413193965 * sCube,
        -0.0041960863 * lCube - 0.7034186147 * mCube + 1.707614701 * sCube,
    ];
}

function inGamut(l: number, c: number, h: number): boolean {
    return oklchToLinearRgb(l, c, h).every((channel) => channel >= -0.0001 && channel <= 1.0001);
}

/** OKLCh → in-gamut `#RRGGBB`, giving up CHROMA (never lightness — lightness is the contrast). */
export function oklchToHex(l: number, c: number, h: number): string {
    let chroma = c;

    if (!inGamut(l, chroma, h)) {
        let lo = 0;
        let hi = chroma;

        // Fixed trip count — see the header, point 2.
        for (let i = 0; i < 32; i++) {
            const mid = (lo + hi) / 2;
            if (inGamut(l, mid, h)) {
                lo = mid;
            } else {
                hi = mid;
            }
        }

        chroma = lo;
    }

    const [r, g, b] = oklchToLinearRgb(l, chroma, h);
    return linearRgbToHex(r, g, b);
}

function search(
    chroma: number,
    hue: number,
    target: number,
    floor: number,
    measure: (hex: string) => number,
    lighterThan: string | null = null,
): string {
    const groundLuminance = lighterThan === null ? null : luminance(lighterThan);

    let best: string | null = null;
    let bestDistance = Infinity;

    for (let step = 0; step <= 1000; step++) {
        const hex = oklchToHex(step / 1000, chroma, hue);

        if (groundLuminance !== null && luminance(hex) <= groundLuminance) continue;

        const ratio = measure(hex);
        if (ratio < floor) continue;

        const distance = Math.abs(ratio - target);
        if (distance < bestDistance) {
            best = hex;
            bestDistance = distance;
        }
    }

    if (best === null) {
        throw new Error(`No lightness clears ${floor} at C=${chroma.toFixed(4)} h=${hue.toFixed(1)}.`);
    }

    return best;
}

export interface BrandRampMeasurement {
    theme: BrandRampTheme;
    pairing: string;
    ratio: number;
    min: number;
}

export interface BrandRampResult {
    input: string;
    engineVersion: number;
    tokens: BrandRampTokens;
    measurements: BrandRampMeasurement[];
}

interface Pairing {
    theme: BrandRampTheme;
    role: BrandRampRole;
    against: 'on_primary' | 'surface' | 'canvas' | 'ink';
    min: number;
    label: string;
}

/** The seventeen design-system-reference.md §4.1 pairings — mirrors `BrandRampGenerator::pairings()`. */
export const BRAND_RAMP_PAIRINGS: Pairing[] = [
    { theme: 'light', role: 'bg', against: 'on_primary', min: TEXT_MIN, label: 'white text on fill' },
    { theme: 'light', role: 'bg_hover', against: 'on_primary', min: TEXT_MIN, label: 'white text on hover fill' },
    { theme: 'light', role: 'bg_active', against: 'on_primary', min: TEXT_MIN, label: 'white text on active fill' },
    { theme: 'light', role: 'fg', against: 'surface', min: TEXT_MIN, label: 'fg text on surface' },
    { theme: 'light', role: 'fg', against: 'canvas', min: TEXT_MIN, label: 'fg text on canvas' },
    { theme: 'light', role: 'fg', against: 'canvas', min: NON_TEXT_MIN, label: 'fg UI boundary vs canvas' },
    { theme: 'light', role: 'ring', against: 'surface', min: NON_TEXT_MIN, label: 'focus ring vs surface' },
    { theme: 'light', role: 'ring', against: 'canvas', min: NON_TEXT_MIN, label: 'focus ring vs canvas' },
    { theme: 'light', role: 'tint', against: 'ink', min: TEXT_MIN, label: 'ink on tint' },
    { theme: 'dark', role: 'bg', against: 'on_primary', min: TEXT_MIN, label: 'white text on fill' },
    { theme: 'dark', role: 'bg_hover', against: 'on_primary', min: TEXT_MIN, label: 'white text on hover fill' },
    { theme: 'dark', role: 'bg_active', against: 'on_primary', min: TEXT_MIN, label: 'white text on active fill' },
    { theme: 'dark', role: 'fg', against: 'surface', min: TEXT_MIN, label: 'fg text on surface' },
    { theme: 'dark', role: 'fg', against: 'canvas', min: TEXT_MIN, label: 'fg text on canvas' },
    { theme: 'dark', role: 'ring', against: 'surface', min: NON_TEXT_MIN, label: 'focus ring vs surface' },
    { theme: 'dark', role: 'ring', against: 'canvas', min: NON_TEXT_MIN, label: 'focus ring vs canvas' },
    { theme: 'dark', role: 'tint', against: 'ink', min: TEXT_MIN, label: 'ink on tint' },
];

function themeTokens(theme: BrandRampTheme, chroma: number, hue: number): Record<BrandRampRole, string> {
    const ground = GROUNDS[theme];
    const target = TARGETS[theme];
    const onPrimary = (hex: string): number => contrast(ON_PRIMARY, hex);

    const bg = search(chroma, hue, target.bg, TEXT_MIN, onPrimary);
    const hover = search(chroma, hue, target.bg_hover, TEXT_MIN, onPrimary);
    const active = search(chroma, hue, target.bg_active, TEXT_MIN, onPrimary);

    const fg =
        theme === 'light'
            ? bg
            : search(chroma, hue, TARGETS.dark.fg, TEXT_MIN, (hex) => contrast(hex, ground.surface), ground.surface);

    const tint = search(
        theme === 'light' ? Math.min(chroma, MAX_TINT_CHROMA_LIGHT) : chroma,
        hue,
        target.tint,
        TEXT_MIN,
        (hex) => contrast(ground.ink, hex),
    );

    return { bg, bg_hover: hover, bg_active: active, fg, tint, ring: theme === 'light' ? hover : fg };
}

/**
 * Derive a brand ramp from one `#RRGGBB`. Mirrors `BrandRampGenerator::generate()`.
 *
 * Throws on a malformed input only. A hue that cannot produce a compliant ramp does not exist — see the
 * PHP docblock for why that is a property of the construction rather than an optimistic claim.
 */
export function generateBrandRamp(input: string): BrandRampResult {
    const normalized = input.trim().toUpperCase();

    if (!/^#[0-9A-F]{6}$/.test(normalized)) {
        throw new Error(`A brand colour must be a #RRGGBB hex triplet, got "${input}".`);
    }

    const [, inputChroma, hue] = hexToOklch(normalized);
    const chroma = Math.min(inputChroma, MAX_CHROMA);

    const tokens = {
        light: themeTokens('light', chroma, hue),
        dark: themeTokens('dark', chroma, hue),
    } as BrandRampTokens;

    const measurements = BRAND_RAMP_PAIRINGS.map((pairing) => {
        const ground = GROUNDS[pairing.theme];
        const against = pairing.against === 'on_primary' ? ON_PRIMARY : ground[pairing.against];

        return {
            theme: pairing.theme,
            pairing: pairing.label,
            ratio: contrast(tokens[pairing.theme][pairing.role], against),
            min: pairing.min,
        };
    });

    return { input: normalized, engineVersion: BRAND_RAMP_ENGINE_VERSION, tokens, measurements };
}

/**
 * What the engine changed about the tenant's input — the data behind the admin card's snap disclosure.
 *
 * **Lives here rather than in the component because there is a PHP twin of it too**
 * (`BrandingPresenter::snap()`), and a third copy inlined in a Vue `computed` would be a third place for
 * the same rule to drift. The rule has one non-obvious part worth stating: `adjusted` compares the input
 * to the LIGHT FILL specifically, never to any of the other eleven tokens. The others are different by
 * construction — they are hover, active, a pale tint, an entire dark ramp — so comparing against them
 * would report an adjustment every single time and the disclosure would degrade into noise.
 */
export function brandRampSnap(result: BrandRampResult): {
    input: string;
    derived: string;
    adjusted: boolean;
} {
    const derived = result.tokens.light.bg;

    return { input: result.input, derived, adjusted: derived !== result.input };
}

/**
 * Measurements ordered by HEADROOM (measured minus minimum), worst first.
 *
 * Worst-first because the claim the report makes is "every combination clears its minimum", and the
 * strongest evidence for that claim is the one that clears by the least. Sorting by raw ratio would put a
 * 15:1 tint at the top and bury the 4.6:1 that a sceptical reader actually wants. Mirrors
 * `BrandingPresenter::contrast()`.
 */
export function brandRampByHeadroom(measurements: BrandRampMeasurement[]): BrandRampMeasurement[] {
    return [...measurements].sort((a, b) => a.ratio - a.min - (b.ratio - b.min));
}
