<?php

declare(strict_types=1);

namespace App\Enums;

use App\Services\Submissions\AnswerIndexProjector;
use App\Support\Analytics\ReportableFields;

/**
 * How ONE field type bears on whether a question can be aggregated by value (ADR-0011 §D3, Increment H24a).
 *
 * The TYPE axis only. Whether a specific FIELD can be reported on also depends on facts no field type
 * carries — the author's `is_queryable` flag, its declared `indexed_data_type`, and whether its section is
 * repeatable — and those live in {@see ReportableFields}. Keeping them out of here
 * is what lets this stay a TOTAL classification of the catalog rather than something that needs a whole
 * `FormField` to answer a question about a type.
 *
 * ── Four-valued on purpose ──────────────────────────────────────────────────────────────────────────────
 * "Reportable vs not" would collapse three genuinely different answers into one message. §D3(ii) requires
 * the authoring surface to say *"this question cannot be reported on"* rather than let "Indexed for
 * reporting" promise something it will not deliver — and the honest sentence differs per case. A geo field
 * in particular is **not** unindexed: §D3 says so explicitly ("The three geo types are excluded from this
 * index but are not unindexed: they have their own GiST-indexed `submission_geo_index`"), so telling an
 * author it cannot be reported on would be false.
 *
 * ── Why a `match` with no `default`, and not a composition ──────────────────────────────────────────────
 * The same argument {@see OcrFieldEligibility} records, and for the same reason it was written down there:
 * composing the predicates {@see FieldType} already has (`! isMedia() && ! isGeo() && ! isComposite()`)
 * reproduces the exact defect H8 was raised to fix, because every one of those predicates carries a
 * `default =>` arm — so a 32nd case would be silently "not media, not geo, not composite" = indexable. A
 * literal classification with NO `default` arm makes an unclassified new type a PHPStan-level-8 error
 * (merge-blocking in `static-analysis`) and an `UnhandledMatchError` at runtime.
 *
 * ── Why it lives here, not on FieldType ─────────────────────────────────────────────────────────────────
 * Reportability is a surface's policy, not an intrinsic structural fact — the same line
 * {@see OcrFieldEligibility} and {@see XlsformTypeMap::isImportable()} already draw.
 */
enum AnalyticsFieldEligibility: string
{
    /**
     * A top-level scalar. {@see AnswerIndexProjector} will write a
     * `submission_answer_index` row for it — IF the author flagged it and declared a type.
     */
    case Indexable = 'indexable';

    /**
     * Array- or object-valued. The projector's `is_array($answer)` guard drops it, and
     * `SubmissionFinalizer::projectIndex()` `continue`s on it one branch earlier — so it yields zero rows
     * forever, flagged or not.
     */
    case Structured = 'structured';

    /**
     * Excluded from the typed answer index but NOT unindexed: geo answers project into the GiST-indexed
     * `submission_geo_index` instead (§D3). No Phase-3 surface reads that table — a geo aggregate is a
     * separate, unbuilt feature — but "cannot be reported on" would still be the wrong thing to tell an
     * author, so it is its own case rather than folded into {@see self::Structured}.
     */
    case Geospatial = 'geospatial';

    /** Holds no respondent answer at all, so there is nothing to aggregate. */
    case NoAnswer = 'no_answer';

    /**
     * The TOTAL classification of the 31-case {@see FieldType} catalog.
     *
     * The partition is generated by one predicate rather than curated: a type is `Indexable` iff its stored
     * answer is a SCALAR, because that — and only that — is what
     * {@see AnswerIndexProjector::project()} accepts. Note it never consults
     * `field_type`; the runtime guard is `is_array($answer)`. This enum is therefore the STATIC twin of a
     * dynamic check, which is exactly why it must agree with it type by type.
     */
    public static function for(FieldType $type): self
    {
        return match ($type) {
            // ── Scalar answers ──────────────────────────────────────────────────────────────────────────
            FieldType::ShortText, FieldType::LongText,
            FieldType::Email, FieldType::Phone, FieldType::Url,
            FieldType::Integer, FieldType::Decimal,
            FieldType::Date, FieldType::Time, FieldType::Datetime, FieldType::Duration,
            FieldType::SingleSelect, FieldType::Dropdown, FieldType::YesNo => self::Indexable,

            // `likert_scale` IS indexable and the ADR calls this out twice as the thing people get wrong:
            // its answer is a SINGLE chosen value, and the rest of this codebase already treats it as a
            // select_one (`hasOptions()` includes it; XlsformTypeMap maps it to `select_one`). It is the
            // two *grid* types below that cannot be indexed.
            FieldType::LikertScale => self::Indexable,

            // H7 sources a hidden field's value from a URL param, a default or an expression, but what is
            // STORED is an ordinary scalar and the projector does not care where it came from. Flagged, it
            // projects.
            FieldType::Hidden => self::Indexable,

            // Server-derived, but `SubmissionFinalizer` merges `$result->computed` into the map BEFORE
            // projecting, so a flagged calculated field does produce rows. Classified by what actually
            // happens, not by what feels like respondent data.
            FieldType::Calculated => self::Indexable,

            // ── Array- or object-valued: the projector's is_array guard drops every one ────────────────
            // `multi_select` stores a LIST even when one option is chosen; `cascading_select` stores the
            // resolved path. Both look scalar to an author and are not.
            FieldType::MultiSelect, FieldType::CascadingSelect => self::Structured,

            // Object-valued grids ({row:{col:cell}} / {row:score}) — the same pair every other channel
            // rejects for the same structural reason.
            FieldType::Matrix, FieldType::LikertMatrix => self::Structured,

            // Arrays of attachment envelopes.
            FieldType::FileUpload, FieldType::ImageCapture,
            FieldType::AudioCapture, FieldType::VideoCapture, FieldType::Signature => self::Structured,

            // ── Object-valued GeoJSON, with an index of their own ───────────────────────────────────────
            FieldType::Geopoint, FieldType::Geotrace, FieldType::Geoshape => self::Geospatial,

            // ── Printed prose and pagination, filled in by nobody ───────────────────────────────────────
            FieldType::Note, FieldType::PageBreak => self::NoAnswer,
        };
    }

    public function isIndexable(): bool
    {
        return $this === self::Indexable;
    }
}
