<?php

declare(strict_types=1);

namespace App\Enums;

use App\Support\Branding\BrandRamp;
use App\Support\Branding\BrandRampGenerator;

/**
 * A form's preset theme (M131, `R-6017d6d8`; `D65` = A, `D81`): the brand ramp's six colour roles, plus a named
 * font pair and a radius scale — each an extra DOCUMENTED property, never an open set. Stored on
 * `forms.theme` as `{"preset": "<value>"}`; null is the workspace's own brand, which is the default.
 *
 * ⛔ THE COLOURS ARE PINNED LITERALS, AND A TEST HOLDS THEM TO THE ENGINE. ADR-0014 §D8 stores a derived ramp
 * rather than re-deriving it on read, so that a change to the engine's targets cannot silently repaint every
 * form that was compliant when it was chosen. A preset honours that the same way: {@see self::tokens()} is the
 * engine's output for {@see self::seed()}, written down. `FormThemePresetTest` asserts the two are equal, so an
 * engine change turns a test red and a re-pin is a reviewed commit, never a quiet repaint. The same test
 * re-measures all seventeen §4.1 pairings on the literals, in both themes.
 *
 * Every plan may pick one (`D81`): a preset is made and contrast-checked by the product, not the workspace's own
 * colour, which stays Starter+ (ADR-0008 §D7).
 */
enum FormThemePreset: string
{
    case Forest = 'forest';
    case Lagoon = 'lagoon';
    case Plum = 'plum';
    case Rosewood = 'rosewood';
    case Graphite = 'graphite';

    /**
     * The only properties a preset may set beyond the six colour roles (`D65` = A). The brand partial emits a
     * preset's {@see self::lines()} and nothing else, and `FormThemePresetTest` refuses any line outside this set.
     */
    public const array DOCUMENTED_PROPERTIES = [
        '--mds-font-family-display',
        '--mds-font-family-body-default',
        '--mds-radius-md',
        '--mds-radius-lg',
        '--mds-radius-xl',
    ];

    public function label(): string
    {
        return match ($this) {
            self::Forest => 'Forest',
            self::Lagoon => 'Lagoon',
            self::Plum => 'Plum',
            self::Rosewood => 'Rosewood',
            self::Graphite => 'Graphite',
        };
    }

    public function description(): string
    {
        return match ($this) {
            self::Forest => 'Green, with the standard type and corners.',
            self::Lagoon => 'Teal, a humanist body face and soft corners.',
            self::Plum => 'Purple, rounded headings and soft corners.',
            self::Rosewood => 'Deep rose, with crisp corners.',
            self::Graphite => 'Slate grey, serif headings and crisp corners.',
        };
    }

    /** The colour the ramp was generated from — the input {@see BrandRampGenerator::generate()} is checked against. */
    public function seed(): string
    {
        return match ($this) {
            self::Forest => '#2E7D32',
            self::Lagoon => '#00796B',
            self::Plum => '#6A1B9A',
            self::Rosewood => '#9C2C5E',
            self::Graphite => '#4A5568',
        };
    }

    public function fontPair(): FormFontPair
    {
        return match ($this) {
            self::Forest, self::Rosewood => FormFontPair::System,
            self::Lagoon => FormFontPair::Humanist,
            self::Plum => FormFontPair::Rounded,
            self::Graphite => FormFontPair::Classic,
        };
    }

    public function radiusScale(): FormRadiusScale
    {
        return match ($this) {
            self::Forest => FormRadiusScale::Standard,
            self::Lagoon, self::Plum => FormRadiusScale::Soft,
            self::Rosewood, self::Graphite => FormRadiusScale::Crisp,
        };
    }

    /**
     * The six colour roles in each theme — PINNED, generated by `BrandRampGenerator` v{@see BrandRampGenerator::VERSION}
     * from {@see self::seed()}. See the class docblock before changing one by hand.
     *
     * @return array<string, array<string, string>> theme ⇒ role ⇒ `#RRGGBB`, in {@see BrandRamp::ROLES} order
     */
    public function tokens(): array
    {
        return match ($this) {
            self::Forest => [
                'light' => ['bg' => '#246126', 'bg_hover' => '#125217', 'bg_active' => '#004007', 'fg' => '#246126', 'tint' => '#EFF7EF', 'ring' => '#125217'],
                'dark' => ['bg' => '#2F6B31', 'bg_hover' => '#145319', 'bg_active' => '#004408', 'fg' => '#63A163', 'tint' => '#084B10', 'ring' => '#63A163'],
            ],
            self::Lagoon => [
                'light' => ['bg' => '#006054', 'bg_hover' => '#005046', 'bg_active' => '#003E36', 'fg' => '#006054', 'tint' => '#ECF7F5', 'ring' => '#005046'],
                'dark' => ['bg' => '#006B5F', 'bg_hover' => '#005147', 'bg_active' => '#004139', 'fg' => '#42A292', 'tint' => '#004940', 'ring' => '#42A292'],
            ],
            self::Plum => [
                'light' => ['bg' => '#694587', 'bg_hover' => '#5A3677', 'bg_active' => '#492564', 'fg' => '#694587', 'tint' => '#F7F3FC', 'ring' => '#5A3677'],
                'dark' => ['bg' => '#744F92', 'bg_hover' => '#5C3878', 'bg_active' => '#4D2968', 'fg' => '#A983CA', 'tint' => '#543070', 'ring' => '#A983CA'],
            ],
            self::Rosewood => [
                'light' => ['bg' => '#873B59', 'bg_hover' => '#762C4A', 'bg_active' => '#631A3A', 'fg' => '#873B59', 'tint' => '#FDF2F5', 'ring' => '#762C4A'],
                'dark' => ['bg' => '#934564', 'bg_hover' => '#782D4C', 'bg_active' => '#671E3E', 'fg' => '#CD7997', 'tint' => '#6F2544', 'ring' => '#CD7997'],
            ],
            self::Graphite => [
                'light' => ['bg' => '#4A5568', 'bg_hover' => '#3C4759', 'bg_active' => '#2C3648', 'fg' => '#4A5568', 'tint' => '#F0F5FE', 'ring' => '#3C4759'],
                'dark' => ['bg' => '#545F73', 'bg_hover' => '#3E485B', 'bg_active' => '#2F3A4B', 'fg' => '#8793A8', 'tint' => '#364052', 'ring' => '#8793A8'],
            ],
        };
    }

    /**
     * The documented extra properties this preset sets — its font pair's and its radius scale's, merged.
     *
     * @return array<string, string> property ⇒ value, every key in {@see self::DOCUMENTED_PROPERTIES}
     */
    public function lines(): array
    {
        return [...$this->fontPair()->declarations(), ...$this->radiusScale()->declarations()];
    }

    /**
     * The preset a stored `forms.theme` names, or null for the workspace's own brand. Anything unrecognised —
     * a removed preset, a hand-edited row — reads as null rather than throwing on a respondent's page.
     *
     * @param  array<string, mixed>|null  $theme
     */
    public static function fromTheme(?array $theme): ?self
    {
        $value = $theme['preset'] ?? null;

        return is_string($value) ? self::tryFrom($value) : null;
    }

    /**
     * Every preset, as the settings panel and the builder preview read it — transmitted, so the client keeps no
     * copy of a value it could let drift.
     *
     * @return list<array{value: string, label: string, description: string, font: string, radius: string, tokens: array<string, array<string, string>>, lines: array<string, string>}>
     */
    public static function catalogue(): array
    {
        return array_map(static fn (self $preset): array => [
            'value' => $preset->value,
            'label' => $preset->label(),
            'description' => $preset->description(),
            'font' => $preset->fontPair()->label(),
            'radius' => $preset->radiusScale()->label(),
            'tokens' => $preset->tokens(),
            'lines' => $preset->lines(),
        ], self::cases());
    }
}
