<?php

declare(strict_types=1);

namespace App\Enums;

/**
 * How ONE field type bears on a form version's OCR eligibility (`docs/ocr-pipeline-design.md` §2,
 * Increment H8). Combined into the version-level verdict by {@see CapabilityFlags::forSnapshot()}.
 *
 * Three-valued on purpose. §2's rule is not "allowed vs forbidden" but "contributes an answer a scan can
 * carry / contributes no answer at all / holds an answer a paper form cannot supply". The middle case is
 * exactly why a literal reading of §2's original 12-item list was wrong: it would have made a form
 * ineligible for containing one instruction `note`.
 *
 * ── Why this is an ALLOWLIST, and why it is a `match` rather than a composition ──────────────────────
 * The pre-H8 rule was a denylist ("no geo, no media, no `calculated`"), so `matrix`/`likert_matrix` were
 * eligible against §2's own words and — worse — every field type added later inherited eligibility
 * instead of earning it. The obvious-looking fix, composing the predicates {@see FieldType} already has
 * (`! isMedia() && ! isGeo() && ! isComposite()`), reproduces that defect exactly: every one of those
 * predicates has a `default =>` arm, so a 32nd case is silently "not media, not geo, not composite" =
 * eligible. Hence a literal classification of its own, below, with NO `default` arm.
 *
 * ── Why it lives here, not on FieldType ─────────────────────────────────────────────────────────────
 * OCR eligibility is channel policy, not an intrinsic structural fact about a field type. The repo
 * already draws that line: {@see XlsformTypeMap::isImportable()} is the XLSForm channel's policy and is
 * not a `FieldType` method either. Keeping it out of the catalog also leaves `FieldType`'s existing
 * 31-arm matches untouched.
 */
enum OcrFieldEligibility: string
{
    /** Respondent-supplied and scalar-shaped: a line, a box, or a circled option on a paper form. */
    case Extractable = 'extractable';

    /**
     * Permitted, but contributes nothing to extract — so it never satisfies §2's "at least one
     * extractable field" clause (`CapabilityFlags`'s non-vacuity check).
     */
    case Neutral = 'neutral';

    /** Present anywhere in the version ⇒ the whole version is `ocr_compatible = false`. */
    case Excluded = 'excluded';

    /**
     * The TOTAL classification of the 31-case {@see FieldType} catalog.
     *
     * Deliberately a `match` with NO `default` arm. Adding a `FieldType` case without classifying it
     * here is a PHPStan-level-8 error ("Match expression does not handle remaining values") — which is
     * merge-blocking in the `static-analysis` CI job — and an `UnhandledMatchError` at runtime. A new
     * field type must therefore EARN eligibility rather than inherit it, which is the whole point of
     * H8. The same device, for the same reason, as {@see XlsformTypeMap::toXlsform()}.
     *
     * The partition is generated by one predicate rather than curated: a type is `Extractable` iff the
     * RESPONDENT supplies its answer AND that answer's stored shape is a scalar a paper form can carry.
     */
    public static function for(FieldType $type): self
    {
        return match ($type) {
            // ── Respondent-supplied scalars ─────────────────────────────────────────────────────────
            // §2's original list omitted `email`/`phone`/`url` (validated short text), `duration` (a
            // scalar written on a line) and `likert_scale` (one circled row of options — the archetypal
            // paper instrument, and a `select_one` everywhere else in this codebase: `hasOptions()`
            // includes it and XlsformTypeMap maps it to `select_one`). H8 amends §2 rather than
            // implementing the omission, which would have disqualified forms the charter never named.
            FieldType::ShortText, FieldType::LongText,
            FieldType::Email, FieldType::Phone, FieldType::Url,
            FieldType::Integer, FieldType::Decimal,
            FieldType::Date, FieldType::Time, FieldType::Datetime, FieldType::Duration,
            FieldType::SingleSelect, FieldType::MultiSelect, FieldType::Dropdown,
            FieldType::YesNo, FieldType::CascadingSelect,
            FieldType::LikertScale => self::Extractable,

            // ── Hold no respondent answer, so they neither help nor block ───────────────────────────
            // `note`/`page_break` are exactly {@see SchemaValueFormatter}'s NON_DATA set — printed
            // prose and pagination, filled in by nobody. `hidden` DOES hold a value, but never one the
            // paper carries (H7 sources it from URL param / default / expression); it is Neutral rather
            // than Excluded because it does not obstruct transcribing the rest, which is the view the
            // human twin of this channel already takes ({@see EncodeFormPresenter}'s OMITTED omits it
            // and does not refuse the form).
            FieldType::Note, FieldType::PageBreak, FieldType::Hidden => self::Neutral,

            // ── Object-valued grids: no flat scan/linelist row representation ────────────────────────
            // The same pair XlsformTypeMap::isImportable() rejects, for the same structural reason
            // (`docs/xlsform-interop-spec.md` §3). These two are H8's headline correction.
            FieldType::Matrix, FieldType::LikertMatrix => self::Excluded,

            // ── Not paper-representable (object-valued GeoJSON envelopes) ───────────────────────────
            FieldType::Geopoint, FieldType::Geotrace, FieldType::Geoshape => self::Excluded,

            // ── The stored answer is an attachment reference; a scan cannot produce an `attachments`
            //    row. `signature` is the one type whose paper artefact IS on the scan — a future
            //    crop-region-to-attachment capability could reclassify it; nothing does today.
            FieldType::FileUpload, FieldType::ImageCapture,
            FieldType::AudioCapture, FieldType::VideoCapture, FieldType::Signature => self::Excluded,

            // ── Server-derived: the pipeline recomputes it, so a scanned value could only contradict
            //    the expression. This is the pre-H8 rule's one non-geo/non-media exclusion, carried
            //    forward unchanged — reclassifying it would be a WIDENING, which is the one class of
            //    change that breaks H8's monotonicity invariant (see CapabilityFlags).
            FieldType::Calculated => self::Excluded,
        };
    }
}
